In [8]:
import numpy as np
import cv2 as cv

face_cascade = cv.CascadeClassifier('./file/xml/haarcascade_frontalface_default.xml')

eye_cascade = cv.CascadeClassifier('./file/xml/haarcascade_eye.xml')

cap = cv.VideoCapture(0)

In [12]:
while(cap.isOpened()):
    
        ret,frame= cap.read()
        img = cv.cvtColor(frame,cv.COLOR_BGR2RGBA)

        gray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)

        faces= face_cascade.detectMultiScale(gray,1.3,5)

        print("Faces",faces)


        for (x,y,w,h) in faces:
            cv.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)

            roi_gray = gray[y:y+h,x:x+w]
            roi_color= img[y:y+h,x:x+w]

            eyes = eye_cascade.detectMultiScale(roi_gray)
            print("Eyes",eyes)

            for (ex,ey,ew,eh) in eyes:
                cv.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)


        cv.imshow("Press q to quit",img)
        

        if cv.waitKey(1) & 0xFF == ord('q'):
                break

cv.destroyAllWindows()

Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces ()
Faces [[196 129 216 216]]
Eyes [[123  56  55  55]
 [ 32  44  72  72]]
Faces ()
Faces [[186 117 238 238]]
Eyes [[134  69  54  54]
 [ 47  59  67  67]]
Faces [[198 129 221 221]]
Eyes [[ 34  47  66  66]
 [124  55  54  54]]
Faces ()
Faces [[199 129 221 221]]
Eyes [[127  57  53  53]
 [ 33  43  70  70]]
Faces [[198 129 221 221]]
Eyes [[ 36  41  70  70]
 [124  54  58  58]]
Faces ()
Faces [[212 134 206 206]]
Eyes ()
Faces ()
Faces [[207 124 226 22

In [ ]:
#cv.imshow("Pic",img)
#cv.waitKey(0)
#cv.destroyAllWindows()