In [20]:
import numpy as np
a = np.zeros([3,6],int)

In [21]:
a

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [22]:
type(a[0])

numpy.ndarray

In [23]:
print("A type: ", type(a))

print("a ndim: ", a.ndim)

print("a shape:", a.shape)

print("a size: ", a.size)

print("a dtype:", a.dtype)

print("itemsize:", a.itemsize, "bytes")
print("nbytes:", a.nbytes, "bytes")


A type:  <class 'numpy.ndarray'>
a ndim:  2
a shape: (3, 6)
a size:  18
a dtype: int64
itemsize: 8 bytes
nbytes: 144 bytes


In [25]:
#Integer Array
x = np.arange(7,100,5)
print(x)

[ 7 12 17 22 27 32 37 42 47 52 57 62 67 72 77 82 87 92 97]


In [26]:
z = np.zeros(10)
z.shape

(10,)

In [29]:
z.shape = (10,)

In [30]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
ones = np.ones(10)

In [14]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
empty = np.empty(3,int)
empty

array([0, 0, 0])

In [33]:
type(empty[0])

numpy.int64

In [34]:
empty[0]

0

In [35]:
ls = np.linspace(2,10,6)
ls

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

In [36]:
np_arr = np.array([1,2,3,4,5,6,7,8,]) 
np_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
type(np_arr[0])

numpy.int64

In [38]:
my_list = [101,102,103,104,105]
list_np_arr = np.array(my_list)
list_np_arr

array([101, 102, 103, 104, 105])

In [53]:
two_d_list = [[1,2,3,4],[5,6,7,8],[9,10,11,12,]]
two_d_list_np_arr = np.array(two_d_list)
two_d_list_np_arr # Normal


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
two_d_list_np_arr[::].T #Transpose

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [52]:
two_d_list_np_arr.shape = (4,3)
two_d_list_np_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
two_d_list_np_arr.shape

(6, 2)

In [49]:
#Random Array

np.random.seed(2)
random_arr = np.random.randint(10,size=6)
random_arr

array([8, 8, 6, 2, 8, 7])

In [41]:
print(two_d_list_np_arr)
print("Sum of all values of array {}".format(np.sum(two_d_list_np_arr)))
print("Product of all values of array {}".format(np.product(two_d_list_np_arr)))
print("Mean of all values of array {}".format(np.mean(two_d_list_np_arr)))
print("Minimum of all values of array {}".format(np.min(two_d_list_np_arr)))
print("Max of all values of array {}".format(np.max(two_d_list_np_arr)))
print("index of Minumum of all values of array {}".format(np.argmin(two_d_list_np_arr)))
print("index of Max of all values of array {}".format(np.argmax(two_d_list_np_arr)))


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Sum of all values of array 78
Product of all values of array 479001600
Mean of all values of array 6.5
Minimum of all values of array 1
Max of all values of array 12
index of Minumum of all values of array 0
index of Max of all values of array 11


In [42]:
#Testing Values
new = np.array([1,2,3,4,5])

In [43]:
new < 3

array([ True,  True, False, False, False])

In [44]:
new > 3

array([False, False, False,  True,  True])

In [45]:
new[new>3]

array([4, 5])

In [46]:
a_arr = np.array([1,2,3,4,5])
b_arr = np.array([6,7,8,9,10])

In [47]:
a_arr + b_arr

array([ 7,  9, 11, 13, 15])

In [48]:
a_arr + 3

array([4, 5, 6, 7, 8])

In [49]:
a_arr * b_arr

array([ 6, 14, 24, 36, 50])

In [50]:
a_arr * 10

array([10, 20, 30, 40, 50])

In [51]:
#a_arr @ b_arr #a · b = ax × bx + ay × by

In [7]:
arr = np.array([6,2,8,4,6,1,0,3])
np.sort(arr)

array([0, 1, 2, 3, 4, 6, 6, 8])

In [8]:
ch_arr = np.array(['a','b','c'])
ch_arr

array(['a', 'b', 'c'], dtype='<U1')

In [9]:
arr

array([6, 2, 8, 4, 6, 1, 0, 3])